### ISSUE TITLE
The username propery is missing

### ISSUE THREAD

**Issue by johnnypraxis** [PlaneteStream/moodle-filter_estreamauth#2]
I'm getting the following notice from the filter_estreamauth plugin in my log:
`PHP Notice: Undefined property: stdClass::$username in /var/www/<site-name>/moodle/filter/estreamauth/filter.php on line 50`

This happens because the user won't fetched in some places of a Moodle site and that results in a notice. I created this pull request to solve the issue:
https://github.com/PlaneteStream/moodle-filter_estreamauth/pull/1

**Comment by PlaneteStream** [comment]
Hi Johnny,

We do not actively use, monitor or update Github, we simply have it as it's a requirement when adding Moodle plugins to the Moodle plugin repository. However, we appreciate you finding this notice and will take a look when we next update the plugins.

**Comment by johnnypraxis** [comment]
Thank you very much.
