### ISSUE TITLE
Compatible release for Moodle v4 .1

### ISSUE THREAD

**Issue by winniebarbour** [PlaneteStream/moodle-filter_estreamauth#3]
Just wondering if we can expect a 4.1 compatible release for filter_estreamauth - we see a few others from the eStream suite have been released in the Moodle plugin library. Will this be available soon?

**Comment by PlaneteStream** [comment]
Hi winniebarbour,

Each eStream plugin except for the TinyMCE one has been tested and working in Moodle 4.2. I've just updated the Moodle plugin repository to reflect that. We're currently underway with a new version of TinyMCE for Moodle 4.1+.

Please let us know if you find specific issues with any of the plugins not working in 4.1.

Thanks,
eStream
